[project]
name = "agentic-interview-prep-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Soumyajit Choudhury", email = "choudhurysoumyajit@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.2",
    "langgraph>=1.2.11",
]

[project.scripts]
agentic-interview-prep-guide = "agentic_interview_prep_guide:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
